/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_3 (
    output reg [7:0] out,
    input [7:0] a,
    input [7:0] b,
    input [5:0] aLUFN
  );
  
  
  
  reg [0:0] zerozero;
  
  reg [0:0] zeroone;
  
  reg [0:0] onezero;
  
  reg [0:0] oneone;
  
  always @* begin
    zerozero = ~a & ~b & {4'h8{aLUFN[0+0-:1]}};
    zeroone = a & ~b & {4'h8{aLUFN[1+0-:1]}};
    onezero = ~a & b & {4'h8{aLUFN[2+0-:1]}};
    oneone = a & b & {4'h8{aLUFN[3+0-:1]}};
    out = (zerozero | zeroone | onezero | oneone);
  end
endmodule
