/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_5 (
    input [7:0] a,
    input [7:0] b,
    input [5:0] aLUFN,
    output reg [0:0] out
  );
  
  
  
  reg [7:0] s;
  
  always @* begin
    
    case (aLUFN[1+1-:2])
      default: begin
        out = 1'h0;
      end
      1'h1: begin
        out = a == b;
      end
      2'h2: begin
        out = a < b;
      end
      2'h3: begin
        out = a <= b;
      end
    endcase
  end
endmodule
