/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_4 (
    input [7:0] a,
    input [7:0] b,
    input [5:0] aLUFN,
    output reg out
  );
  
  
  
  reg [7:0] mux_00;
  
  reg [7:0] mux_01;
  
  reg [7:0] mux_10;
  
  reg [7:0] mux_11;
  
  always @* begin
    mux_00 = ~a & ~b & {4'h8{aLUFN[0+0-:1]}};
    mux_01 = a & ~b & {4'h8{aLUFN[1+0-:1]}};
    mux_10 = ~a & b & {4'h8{aLUFN[2+0-:1]}};
    mux_11 = a & b & {4'h8{aLUFN[3+0-:1]}};
    out = (mux_00 | mux_01 | mux_10 | mux_11);
  end
endmodule
